In [3]:
import numpy as np
import math

In [4]:
word_length = 4
d_k = 4
d_v = 4

In [6]:
q = np.random.randn(word_length,d_k)
k = np.random.randn(word_length,d_k)
v = np.random.randn(word_length,d_v)

In [7]:
q,k,v

(array([[-0.89851985,  1.24643261,  0.73448966,  0.84493691],
        [ 0.45293123, -2.54448195,  0.87368793, -0.12069959],
        [-0.27368476,  1.60814322,  1.52297335,  1.52482414],
        [-0.55501072, -1.63416275,  2.41434228, -0.36553828]]),
 array([[ 0.99390035, -1.20326989,  1.73393676, -0.27021454],
        [-0.02314744,  1.14796711, -0.51777105, -1.43905519],
        [ 0.98878515,  1.19418911,  1.60795918, -0.64834353],
        [ 1.25478702, -1.2702181 , -1.14530342,  0.63643865]]),
 array([[-1.34621976, -0.18472472,  0.01541767, -0.31632188],
        [-0.20285227, -0.43858106,  0.03521245, -0.58719645],
        [-0.05879793, -1.29813798,  0.72028208, -0.3979344 ],
        [ 0.82753433,  0.84304767, -0.11530589,  0.31041019]]))